development:
  adapter: postgresql
  encoding: unicode
  database: TallerHM_development
  pool: 5
  username: iMarquezc
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: TallerHM_test
  pool: 5
  username: iMarquezc
  password: 123456

production:
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: TallerMM_production
  pool: 5
  username: <%= ENV['TALLERMH_DATABASE_USER'] %>
  password: <%= ENV['TALLERMH_DATABASE_PASSWORD'] %>