development:
  adapter: postgresql
  encoding: unicode
  database: TallerHM_development
  pool: 5
  username: iMarquezc
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: TallerHM_test
  pool: 5
  username: iMarquezc
  password: 123456
